##############
### 공통...   
##############
# embeded tomcat
server:
#  context-path: /aaa
  tomcat:
    uri-encoding: UTF-8  

#spring:
#  profiles:
#    active: local
#  # favicon
#  mvc.favicon.enabled: false
#  # HTTP encoding (HttpEncodingProperties)
#  http:
#    encoding:
#      charset: UTF-8 # the encoding of HTTP requests/responses
#      enabled: true # enable http encoding support
#      force: true # force the configured encoding
#  jackson:
#    serialization:
#      write-dates-as-timestamps: false
#  session:
#    store-type: none
#
#logging:
#  config: classpath:logback-spring.xml
  
---

##############
### local
##############

  
  
# embeded tomcat
server:
  port: 8080


spring:
  profiles: local
  datasource:
#    hikari:
#      jdbc-url: jdbc:mysql://127.0.0.1:3306/remoto?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
#      username: root
#      password: 141201
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      register-mbeans: true
    url: jdbc:mysql://127.0.0.1:3306/remoto?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 141201


#logging:
#  level:
#    com.lotte.sample: info
